name: windows_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  process_run: ^0.13.1
  path_provider: ^2.1.1
  screenshot:
    path: ../../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
